from pole_position.cli import console
from pole_position.cli.command import Command
from pole_position.cli.services.db_runner import run_alembic_command
from pole_position.cli.usage import print_command_help

USAGE = 'Usage: polepos db revision -m "<message>"'


def run(args: list[str]) -> None:
    if args and args[0] in {"-h", "--help"}:
        if len(args) > 1:
            console.error(f"Unexpected argument: {args[1]}")
            print(USAGE)
            raise SystemExit(1)
        print_command_help("db", "revision")
        return

    if len(args) != 2 or args[0] not in {"-m", "--message"}:
        print(USAGE)
        raise SystemExit(1)

    if args[1].startswith("-"):
        print(USAGE)
        raise SystemExit(1)

    message = args[1].strip()
    if not message:
        print(USAGE)
        raise SystemExit(1)

    try:
        run_alembic_command("revision", ["--autogenerate", "-m", message])
    except RuntimeError as exc:
        console.error(str(exc))
        raise SystemExit(1) from exc


command = Command(
    name="revision",
    handler=run,
    description="Create a new autogenerated migration revision",
)
