from pole_position.cli.command import Command
from pole_position.cli.services.db_runner import run_alembic_command


USAGE = 'Usage: polepos db revision -m "<message>"'


def run(args: list[str]) -> None:
    if len(args) != 2 or args[0] not in {"-m", "--message"}:
        print(USAGE)
        raise SystemExit(1)

    message = args[1].strip()
    if not message:
        print(USAGE)
        raise SystemExit(1)

    try:
        run_alembic_command("revision", ["--autogenerate", "-m", message])
    except RuntimeError as exc:
        print(str(exc))
        raise SystemExit(1)


command = Command(
    name="revision",
    handler=run,
    description="Create a new autogenerated migration revision",
)
